### ISSUE TITLE
Linux and android binaries are huge

### ISSUE THREAD

**Issue by amerkoleci** [MonoGame/MonoGame.Library.OpenAL#2]
Hi,
I saw that linux-x64 is 27MB big and android binaries are between 14-16MB, is it normal?

Windows is 1.6MB and osx is 2.6MB which seams more normal.

Thanks,

Amer

**Comment by dellis1972** [comment]
@amerkoleci thanks for the bug report. 
In the latest commit I have the linux one down to 2 meg. But the android are still 14-16meg. Hopefully someone else can take a look.

**Comment by amerkoleci** [comment]
Thanks!

**Comment by amerkoleci** [comment]
Even android binaries are small now, what's wrong with android?

**Comment by dellis1972** [comment]
PR #4 fixes them even further. Size is an extremely sensitive area for android developers because of googles package size limitations. The smaller we can get them the better.
